# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
np.empty((3,3,3))

array([[[3.17095864e+180, 6.87334409e-154, 1.17365077e+214],
        [6.01347002e-154, 9.29797751e+199, 3.91049625e+180],
        [9.47072713e-154, 1.07219189e+200, 2.96338471e+222]],

       [[2.64521554e+185, 1.78488214e+161, 7.89005710e+165],
        [6.01346953e-154, 1.43974042e+214, 1.27734658e-152],
        [2.42766856e-154, 2.28896090e+243, 2.47379808e-091]],

       [[2.44041296e-154, 1.03845125e-028, 4.83245961e+276],
        [6.01347002e-154, 2.69283788e+020, 2.44141292e-152],
        [2.66065731e-260, 1.27661731e-152, 6.01334659e-154]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
np.diag(1+np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix 

In [5]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.87868459 0.3034197  0.45766472 0.82245557 0.90742725]
 [0.32955768 0.63276783 0.57644486 0.75282076 0.75697611]
 [0.31244256 0.09082193 0.51551726 0.63787435 0.33210353]
 [0.16805797 0.13832327 0.12304    0.26397747 0.45505166]
 [0.24551064 0.96684628 0.85635215 0.64476415 0.730156  ]]
After normalization:
[[0.8993616  0.24268477 0.41875867 0.83517501 0.93217195]
 [0.27252182 0.61864251 0.55434867 0.75568542 0.76042885]
 [0.25298456 0.         0.48479855 0.62447171 0.27542796]
 [0.08816655 0.05422377 0.0367776  0.19766065 0.4157758 ]
 [0.17658037 1.         0.87386866 0.63233656 0.72981313]]


# 5. How to find common values between two arrays

In [6]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

np.intersect1d(a, b)

array([4, 5, 6, 7, 9])

# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yest = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tom  = np.datetime64('today') + np.timedelta64(1)
print(yest, today, tom)

2020-08-01 2020-08-02 2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [8]:
a=np.random.random((3,3))
b=np.random.random((3,3))
if a.all()==b.all():
    print('They are equal')
else:
    print('They are not equal')

They are equal


# 8.Create random vector of size 10 and replace the maximum value by 0

In [9]:
a = np.random.rand(10)
a[a.argmax()] = 0
a

array([0.17646962, 0.22332892, 0.        , 0.30731866, 0.32686535,
       0.45382132, 0.25903735, 0.07957938, 0.54767162, 0.53113605])

# 9. How to print all the values of an array?

In [10]:
a=np.random.random((2,2))
print(a)

[[0.32574734 0.58411104]
 [0.25538702 0.41043059]]


# 10.Subtract the mean of each row of a matrix 

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1=a[0].mean()
m2=a[1].mean()
m3=a[2].mean()
print(m1-m2-m3)

-11.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
a = np.ones(5)
b = np.random.randint(0, len(a), 10)
a += np.bincount(b, minlength = len(a))
a

array([2., 1., 2., 5., 5.])

# 12.How to get the diagonal of a dot product?

In [13]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", a, b)

array([ 48,  38, 102])

# 13.How to find the most frequent value in an array? 

In [14]:
a = np.random.randint(0,10,20)
print(a)
max(set(a), key = list(a).count)

[8 2 7 3 6 5 0 8 3 8 9 4 8 9 4 6 1 2 8 1]


8

# 14.How to get the n largest values of an array

In [15]:
a=np.random.random((3,3))
print(a.max())

0.9992043248507803


# 15.How to create a record array from a regular array?

In [16]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])